### PR TITLE
Added option to enable grunt tasks to fail

### PR DESCRIPTION
**Pull request by bakharal**
Hi there! What about such a small change? Would be reasonable to allow grunt tasks to fail (not gracefully).

### CODE REVIEW

**Comment by bakharal** [comment]
BTW, if you are ok with this change, I will cover it with a proper test case.

**Comment by gratimax** [comment]
:+1: looks great, just wondering what the use case is? Besides that, a test case would be great.

**Comment by bakharal** [comment]
Oh, nothing really special. We have an old `grunt` task, which we want to use from the `gulp`-based build process. It is running on CI cluster, and we want to have an ability to fail whole build if grunt task is failed. I will come with a test case soon.

**Comment by bakharal** [comment]
@gratimax Hey, done with tests: https://github.com/gratimax/gulp-grunt/pull/30/commits/5a7080cacab1e503b18687d504908ba6176fb9ec

**Comment by gratimax** [comment]
:+1: merging

**Pull request merged**
